# Configuração Quarkus SmallRye JWT com RSA (RS256)
# Aponta para o arquivo public.pem que está em src/main/resources
mp.jwt.verify.publickey.location=public.pem
mp.jwt.verify.issuer=legacy-system
mp.jwt.verify.audiences=camel-middleware
smallrye.jwt.verify.algorithm=RS256

# Configuração do Kafka
kafka.brokers=kafka:9092
kafka.topic.dlq=camel-dlq-pacientes